### ISSUE TITLE
Improving UI/UX, Optimizations, Security etc

### ISSUE THREAD

**Issue by johnsonsirv** [johnsonsirv/famous-poet#5]
Kindly add comments here.

**Comment by igakigongo** [comment]
Hi Victor,

Just noted that it's possible to save the svg images as files and use an appropriate webpack-loader.
It's cheaper than hard-coding them into the components.

Apart from that, thank you very much for the presentation. I was very impressed.

Kind regards,
Edward Iga - Jubei.
